name: quizz_app
description: An educational quiz about famous paintings and art.
publish_to: 'none'


version: 1.0.2+3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  firebase_core: ^2.5.0
  cloud_firestore: ^4.3.2
  firebase_auth: ^4.2.6
  google_sign_in: 5.3.3
  sign_in_with_apple: 4.0.0
  crypto: 3.0.1
  font_awesome_flutter: 10.1.0
  google_fonts: ^6.0.1
  flutter_fortune_wheel: ^1.2.0
  provider: 6.0.3
  rxdart: 0.27.4
  json_annotation: 4.5.0
  flutter_animate: ^4.1.1+1
  transparent_image: ^2.0.1
  full_screen_image: ^2.0.0
  photo_view: ^0.14.0
  firebase_storage: ^11.2.6
  flex_color_scheme: ^7.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  icons_launcher: ^2.1.0

  build_runner: 2.1.11
  json_serializable: 6.2.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/covers/
    - assets/congrats.gif

icons_launcher:
  image_path: 'assets/icon.png'
  platforms:
    android:
     enable: true
    ios:
     enable: true